// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformBot.Infrastructure.DAL.Implementations;

#nullable disable

namespace PlatformBot.Infrastructure.DAL.Implementations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250420152524_MoveFromJsonB")]
    partial class MoveFromJsonB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PlatformBot.Infrastructure.DAL.Abstractions.MergeRequestRedirectionMessageData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<int>("MergeRequestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MergeRequestId");

                    b.Property<string>("MergeRequestUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MergeRequestUrl");

                    b.Property<ulong>("OriginalChannelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OriginalChannelId");

                    b.Property<string>("OriginalMessageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("OriginalMessageUrl");

                    b.HasKey("Id");

                    b.ToTable("MergeRequestRedirectionMessageData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
