// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformBot.Infrastructure.DAL.Implementations;

#nullable disable

namespace PlatformBot.Infrastructure.DAL.Implementations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250417195156_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PlatformBot.Infrastructure.DAL.Abstractions.MessageData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Data");

                    b.HasKey("Id");

                    b.ToTable("MessageData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
