// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformBot.Infrastructure.DAL.Implementations;

#nullable disable

namespace PlatformBot.Infrastructure.DAL.Implementations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250420160725_FixA")]
    partial class FixA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PlatformBot.Infrastructure.DAL.Abstractions.MergeRequestRedirectionMessageData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<int>("MergeRequestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MergeRequestId");

                    b.Property<string>("MergeRequestUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MergeRequestUrl");

                    b.HasKey("Id");

                    b.ToTable("MergeRequestRedirectionMessageData", (string)null);
                });

            modelBuilder.Entity("PlatformBot.Infrastructure.DAL.Abstractions.MergeRequestRedirectionMessageData", b =>
                {
                    b.OwnsOne("PlatformBot.Infrastructure.DAL.Abstractions.MessageLocation", "RedirectMessageLocation", b1 =>
                        {
                            b1.Property<Guid>("MergeRequestRedirectionMessageDataId")
                                .HasColumnType("TEXT");

                            b1.Property<ulong>("ChannelId")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("MessageId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MergeRequestRedirectionMessageDataId");

                            b1.ToTable("MergeRequestRedirectionMessageData");

                            b1.WithOwner()
                                .HasForeignKey("MergeRequestRedirectionMessageDataId");
                        });

                    b.OwnsOne("PlatformBot.Infrastructure.DAL.Abstractions.MessageLocation", "RequestMessageLocation", b1 =>
                        {
                            b1.Property<Guid>("MergeRequestRedirectionMessageDataId")
                                .HasColumnType("TEXT");

                            b1.Property<ulong>("ChannelId")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("MessageId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MergeRequestRedirectionMessageDataId");

                            b1.ToTable("MergeRequestRedirectionMessageData");

                            b1.WithOwner()
                                .HasForeignKey("MergeRequestRedirectionMessageDataId");
                        });

                    b.Navigation("RedirectMessageLocation")
                        .IsRequired();

                    b.Navigation("RequestMessageLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
